### ISSUE TITLE
Establish branch protections for 'main' branch

### ISSUE THREAD

**Issue by BenjaminMuscato** [nmuscato/TidyCore#1]
## User Story(s)

**As a** TidyCore developer
**I want** our 'main' branch to be un-deletable
**So that** we don't fuck our whole shit up

**As a** TidyCore developer
**I want** our 'main' branch to require Code Reviews before merges
**So that** we have a constant, guaranteed knowledge transfer mechanism
    - **And** we have a constant quality checkpoint

## Details / Word-vomit / Alternative design description

Right out the gate, I think we should establish some "best practices" for our 'main' branch. In particular, what I'm thinking is that our 'main' branch:

- **MUST** not be able to be deleted
- **MUST** require at least one approved Code Review, before allowing feature branches to be merged-in
    - **EXCEPTION**: Repo admins MUST be able to easily and intuitively override this requirement, in case of emergencies

You can accomplish these by going to Settings > Branches > "Add branch protection rule" and checking-off the appropriate fields.

Some notes:

- Branch protection rules disable branch deletions by default, so that requirement will be fulfilled by simply saving a new rule for the 'main' branch (so long as you do NOT check the 'Allow deletions' option)
- The requirement for code reviews _and _ the ability for overriding that can be found under the same option.

## Acceptance Criteria

A reviewer (me) will need to:

1. Check that the protections settings _look_ correct
2. **Prove** the settings are correct, by trying to:
    1. Push a commit to 'main'
    2. Force-push a commit to 'main'
    3. Merge-in a PR without getting approval _and_ without using the override
    4. Verify that the override option appears when doing the previous check
    5. Delete the main branch via both command-line and Web GUI operations

**Comment by nmuscato** [comment]
"Your protected branch rules won't be enforced on this private repository until you move to a GitHub Team or Enterprise organization account."

Womp, womp...

**Comment by BenjaminMuscato** [comment]
Reminder that we'll wanna try making this repo public, and see if the
branch protections will be enforced then.

Having a repo public *does* add some level of concern, but for our purposes
AFAIK we mostly need to worry about Secrets (API keys, username/passwords,
etc. etc.). We have to be doubly sure that none of that is *ever* part of
the repo code, put in plaintext in GitHub Issues or Wiki, etc. etc.
Otherwise, an army of public GitHub scraping bots will quite literally
steal and use those secrets in like 5 seconds.

There are additional automated protections we can enable to help add
redundancies to guard against this, we'll just need to investigate.

**Comment by nmuscato** [comment]
I think I did the thing.

**Comment by BenjaminMuscato** [comment]
~~@nmuscato Whoops I forgot one thing: Can you add me as an Editor? (I think it might be called "Admin"). You can normally find those settings under "Settings > Collaborators"~~

**Comment by nmuscato** [comment]
Oh hey I think I did the thing.
